name: Build RPA Windows EXE

on:
  push:
    branches: [ main ] # Se activa cada vez que subes cambios a la rama main

jobs:
  build:
    runs-on: windows-latest # Aqu√≠ ocurre la magia: usamos Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright pandas openpyxl pyinstaller
        playwright install chromium

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onedir --noconsole main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RPA-Asocebu-Windows
        path: dist/main/